
name: Stop EC2 Instance

on:
  workflow_dispatch:

jobs:
  stop-instance:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1a    

    - name: Stop EC2 instance
      run: |
        INSTANCE_ID="i-03826e448ce3bb0c9"
        aws ec2 stop-instances --instance-ids $i-03826e448ce3bb0c9
